### ISSUE TITLE
CPSessionManagerTest fail on windows

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#1022]
![image](https://user-images.githubusercontent.com/32355782/129885275-92693474-77cc-4798-a4cd-bd84ef354a4e.png)

failed on gh actions of pr

#1000

**Comment by srknzl** [comment]
Another similar one: 

```
1) CPSessionManagerTest
       CPProxySessionManager
         acquireSession: should create new session for existing invalid session:
     Uncaught TypeError: Cannot read property 'invokeOnRandomTarget' of undefined
      at CPSessionManager.requestHeartbeat (src\proxy\cpsubsystem\CPSessionManager.ts:40:17)
      at heartbeatTask (src\proxy\cpsubsystem\CPSessionManager.ts:40:17)
      at Timeout.task.timeoutId.setTimeout [as _onTimeout] (src\util\Util.ts:20:30)
```

**Comment by srknzl** [comment]
We need to backport this to all other branches as well
