### ISSUE TITLE
LostInvalidationTest test fail [API-1199]

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#1041]
1) LostInvalidationTest
       client eventually receives an update for which the invalidation event was dropped:
     TypeError: Cannot read property 'get' of undefined
      at blockInvalidationEvents (test\integration\nearcache\LostInvalidationsTest.js:36:29)
      at Context.<anonymous> (test\integration\nearcache\LostInvalidationsTest.js:94:41)

in https://github.com/srknzl/hazelcast-nodejs-client/actions/runs/1212445164

**Comment by srknzl** [comment]
![image](https://user-images.githubusercontent.com/32355782/153202773-f25cf7a2-1776-459d-b600-016ffe742725.png)

**Comment by srknzl** [comment]
1) LostInvalidationTest
       client eventually receives an update for which the invalidation event was dropped:
     TypeError: Cannot read property 'connectionRegistrations' of undefined
      at blockInvalidationEvents (test\integration\backward_incompatible\parallel\nearcache\LostInvalidationsTest.js:37:29)
      at Context.<anonymous> (test\integration\backward_incompatible\parallel\nearcache\LostInvalidationsTest.js:98:41)


failed on nightly on master with commit 60e0da084070862d6d056faba97889ec533133fd with Node 14 and ubuntu-latest
