### ISSUE TITLE
ListenersOnReconnectTest test failure [API-1196]

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#1114]
https://github.com/hazelcast/hazelcast-nodejs-client/runs/4023862333?check_suite_focus=true
also 
https://github.com/hazelcast/hazelcast-nodejs-client/runs/4029727476?check_suite_focus=true

Seems to happen on windows

```  
1) ListenersOnReconnectTest
       kill two members [0,1], listener still receives map.put event [smart=true]:
     Uncaught TypeError: Cannot add property 0, object is not extensible
      at Array.push (<anonymous>)
      at PipelinedWriter.write (lib\network\Connection.js:19:183)
      at Connection.write (src\network\Connection.ts:72:17)
      at InvocationService.send (src\invocation\InvocationService.ts:130:20)
      at InvocationService.invokeSmart (src\invocation\InvocationService.ts:130:20)

  2) ListenersOnReconnectTest
       kill two members [0,1], listener still receives map.put event [smart=true]:
     Error: done() called multiple times in test <ListenersOnReconnectTest kill two members [0,1], listener still receives map.put event [smart=true]> of file D:\a\hazelcast-nodejs-client\hazelcast-nodejs-client\test\integration\backward_compatible\parallel\ListenersOnReconnectTest.js; in addition, done() received error: Error: Client is shutting down.
```

**Comment by srknzl** [comment]
Also on windows and 2f94a87e4f1a138f1e7163119906d9fb346c52f4

  1) ListenersOnReconnectTest
       kill two members [0,1], listener still receives map.put event [smart=false]:
     Uncaught TypeError: Cannot add property 0, object is not extensible
      at Array.push (<anonymous>)
      at PipelinedWriter.write (lib\network\Connection.js:19:183)
      at Connection.write (src\network\Connection.ts:72:17)
      at InvocationService.send (src\invocation\InvocationService.ts:130:20)
      at InvocationService.invokeNonSmart (src\invocation\InvocationService.ts:130:20)

  2) ListenersOnReconnectTest
       kill two members [0,1], listener still receives map.put event [smart=false]:
     Error: done() called multiple times in test <ListenersOnReconnectTest kill two members [0,1], listener still receives map.put event [smart=false]> of file D:\a\hazelcast-nodejs-client\hazelcast-nodejs-client\test\integration\backward_compatible\parallel\ListenersOnReconnectTest.js; in addition, done() received error: Error: Client is shutting down.

**Comment by srknzl** [comment]
```
  1) ListenersOnReconnectTest
       kill two members [0,2], listener still receives map.put event [smart=false]:
     Error: null
      at new TargetDisconnectedError (src\core\HazelcastError.ts:64:20)
      at Timeout._onTimeout (src\invocation\InvocationService.ts:122:40)
```

Windows fails are frequent
