### ISSUE TITLE
TranslateAddressProviderTest failure [API-1111]

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#1165]
On windows and cd6240ed9569b6f8fdb9ef7339ea7e6e3beb6448
```
 1) TranslateAddressProviderTest
       should provide true for default config and publicly reachable single member:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test\unit\network\TranslateAddressProviderTest.js:236:37)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) TranslateAddressProviderTest
       should provide true for default config and publicly reachable members:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test\unit\network\TranslateAddressProviderTest.js:251:37)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by srknzl** [comment]
Does not fail on my local computer on windows. Seems like related to gh actions env

**Comment by srknzl** [comment]
I think the fail is because somehow `const UNREACHABLE_HOST = '192.168.0.1';` was reachable
going to change it to a random thing

**Comment by srknzl** [comment]
The fail happened again in https://github.com/hazelcast/hazelcast-nodejs-client/actions/runs/3148328777/jobs/5118740859#step:9:5841

**Comment by srknzl** [comment]
Needs backporting.
