### ISSUE TITLE
ListenerServiceTest listener is not invoked when it is removed and new member starts[smart=false] [API-1195]

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#1171]
windows and node 10 on https://github.com/hazelcast/hazelcast-nodejs-client/commit/e6956513c7e97995cf997172cf6a5ab15be8cd87

```

  1) ListenerServiceTest[smart=false]
       listener is not invoked when it is removed and new member starts[smart=false]:
     TApplicationException: Internal error processing startMember
      at exports.Client.RemoteControllerClient.recv_startMember (test\integration\remote_controller\RemoteController.js:1987:13)
      at D:\a\hazelcast-nodejs-client\hazelcast-nodejs-client\node_modules\thrift\lib\nodejs\lib\thrift\connection.js:140:41
      at Socket.<anonymous> (node_modules\thrift\lib\nodejs\lib\thrift\framed_transport.js:63:7)
      at Socket.EventEmitter.emit (domain.js:448:20)
      at addChunk (_stream_readable.js:288:12)
      at readableAddChunk (_stream_readable.js:269:11)
      at Socket.Readable.push (_stream_readable.js:224:10)
      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by yuce** [comment]
Remote controller problem, not a test failure.
