### ISSUE TITLE
NearCachedMapTest test fail [API-1161]

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#1176]
failed with node 10.24.1, on windows, client commit 8ad6e6b846e2c1b79e1d46534386562cda422d7b

```
1) NearCachedMapTest
       invalidate on change=true
         get returns null if the entry was removed by another client:

      AssertionError: expected 1 to equal 0
      + expected - actual

      -1
      +0
      
      at expectStats (test\integration\backward_compatible\parallel\map\NearCachedMapTest.js:71:43)
      at Context.<anonymous> (test\integration\backward_compatible\parallel\map\NearCachedMapTest.js:106:17)
```

can easily reproduce on another setup such as node 16 and macos.

**Comment by srknzl** [comment]
Test failed again https://github.com/hazelcast/hazelcast-nodejs-client/runs/4946176268?check_suite_focus=true
