### ISSUE TITLE
MapPartitionAwareTest [API-1239]

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#1198]
windows node17   https://github.com/hazelcast/hazelcast-nodejs-client/commit/940dce919e5c7142ef087c780fad4024b5cde74e

 1) MapPartitionAwareTest
       "before all" hook for "put":
     TApplicationException: Internal error processing startMember
      at exports.Client.RemoteControllerClient.recv_startMember (test\integration\remote_controller\RemoteController.js:1987:13)
      at D:\a\hazelcast-nodejs-client\hazelcast-nodejs-client\node_modules\thrift\lib\nodejs\lib\thrift\connection.js:140:41
      at Socket.<anonymous> (node_modules\thrift\lib\nodejs\lib\thrift\framed_transport.js:63:7)
      at Socket.emit (node:events:527:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Socket.Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by yuce** [comment]
Failure due to remote controller, not the test. Closing.
