### ISSUE TITLE
ClusterServiceTest [API-1240]

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#1199]
windows-latest with Node 12 https://github.com/hazelcast/hazelcast-nodejs-client/commit/940dce919e5c7142ef087c780fad4024b5cde74e

1) ClusterServiceTest
       should know when a member leaves cluster:
     Uncaught TypeError: Cannot add property 0, object is not extensible
      at Array.push (<anonymous>)
      at PipelinedWriter.write (src\network\Connection.ts:87:20)
      at Connection.write (src\network\Connection.ts:399:21)
      at InvocationService.send (src\invocation\InvocationService.ts:537:27)
      at InvocationService.invokeSmart (src\invocation\InvocationService.ts:460:38)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

**Comment by srknzl** [comment]
Another similar fail
on https://github.com/hazelcast/hazelcast-nodejs-client/commit/c9b230fda1318519b7fed61b9c0afdc1dcce2b72 ubuntu latest
```
1) ClusterServiceTest
       getMembers returns correct list after a member is removed:
     Uncaught TypeError: Cannot add property 0, object is not extensible
      at Array.push (<anonymous>)
      at PipelinedWriter.write (src\network\Connection.ts:87:20)
      at Connection.write (src\network\Connection.ts:399:21)
      at InvocationService.send (src\invocation\InvocationService.ts:537:27)
      at InvocationService.invokeSmart (src\invocation\InvocationService.ts:460:38)
      at listOnTimeout (internal/timers.js:535:17)
      at processTimers (internal/timers.js:479:7)
```

**Comment by srknzl** [comment]
I could not reproduce the test, will work on this more

**Comment by srknzl** [comment]
```
1) ClusterServiceTest
       getMembers returns correct list after a member is removed:
     Uncaught TypeError: Cannot add property 0, object is not extensible
      at Array.push (<anonymous>)
      at PipelinedWriter.write (src\network\Connection.ts:87:20)
      at Connection.write (src\network\Connection.ts:399:21)
      at InvocationService.send (src\invocation\InvocationService.ts:537:27)
      at InvocationService.invokeSmart (src\invocation\InvocationService.ts:460:38)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

https://github.com/hazelcast/hazelcast-nodejs-client/runs/5594987776?check_suite_focus=true



As the fix we can add a try catch and ignore the writes after connection close()

**Comment by srknzl** [comment]
superseeded by #1256
