### ISSUE TITLE
ClientReconnectTest fail  [API-1241]

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#1200]
4.0.x node 11 ubuntu 0779f68d33e2c9a3c660fe1b10dc9a8be6327f8a

1) ClientReconnectTest
       member restarts, while map.put in progress 2:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/hazelcast-nodejs-client/hazelcast-nodejs-client/test/ClientReconnectTest.js)
      at listOnTimeout (internal/timers.js:535:17)
      at processTimers (internal/timers.js:479:7)

**Comment by srknzl** [comment]
1) ClientReconnectTest
       create proxy while member is down, member comes back:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/hazelcast-nodejs-client/hazelcast-nodejs-client/test/integration/ClientReconnectTest.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)


4.1.x ubuntulatest node 15
