### ISSUE TITLE
[Test-Failure] Lock Proxy acquires lock before timeout is exceeded

### ISSUE THREAD

**Issue by mustafaiman** [hazelcast/hazelcast-nodejs-client#124]
https://hazelcast-l337.ci.cloudbees.com/view/Clients/job/NodeJS-pr-builder/102/console

> 17:24:27   1) Lock Proxy acquires lock before timeout is exceeded:
17:24:27      AssertionError: expected 2 to be above 1000
17:24:27       at test/LockProxyTest.js:90:35
17:24:27       at _fulfilled (node_modules/q/q.js:834:54)
17:24:27       at self.promiseDispatch.done (node_modules/q/q.js:863:30)
17:24:27       at Promise.promise.promiseDispatch (node_modules/q/q.js:796:13)
17:24:27       at node_modules/q/q.js:604:44
17:24:27       at runSingle (node_modules/q/q.js:137:13)
17:24:27       at flush (node_modules/q/q.js:125:13)

**Comment by mustafaiman** [comment]
This test fails a lot in PR builder.
