### ISSUE TITLE
CPSessionManagerTest.CPProxySessionManager `acquireSession: should create new session for existing invalid session`

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#1315]
Fails sometimes and only on windows 

```
  1) CPSessionManagerTest
       CPProxySessionManager
         acquireSession: should create new session for existing invalid session:
     Uncaught TypeError: Cannot read property 'catch' of undefined
      at D:\a\hazelcast-nodejs-client\hazelcast-nodejs-client\lib\proxy\cpsubsystem\CPSessionManager.js:180:25
      at Timeout._onTimeout (src\util\Util.ts:211:9)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

```
`requestHeartbeat` seems to return (not resolve to) undefined somehow.

**Comment by srknzl** [comment]
Internal jira issue: https://hazelcast.atlassian.net/browse/API-1372
