### ISSUE TITLE
read emoji string has error

### ISSUE THREAD

**Issue by cycerto** [hazelcast/hazelcast-nodejs-client#157]
when try to read the following string
```
let str1 =  "1⚐中💦2😭‍🙆😔5"
let str2 = "﹏ JOJO糾ั͡✾✎"
```

error emit:

```
fetch caster-store data (key: (instance1) key-1) has error:  { AssertionError: false == true
    at ObjectDataInput.assertAvailable (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/hazelcast-client/lib/serialization/ObjectData.js:261:9)
    at ObjectDataInput.read (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/hazelcast-client/lib/serialization/ObjectData.js:274:14)
    at ObjectDataInput.readByte (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/hazelcast-client/lib/serialization/ObjectData.js:289:21)
    at ObjectDataInput.readUTF (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/hazelcast-client/lib/serialization/ObjectData.js:426:36)
    at StringSerializer.read (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/hazelcast-client/lib/serialization/DefaultSerializer.js:16:22)
    at SerializationServiceV1.toObject (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/hazelcast-client/lib/serialization/SerializationService.js:45:27)
    at MapProxy.BaseProxy.toObject (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/hazelcast-client/lib/proxy/BaseProxy.js:54:54)
    at Function.MapGetCodec.decodeResponse (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/hazelcast-client/lib/codec/MapGetCodec.js:32:38)
    at /Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/hazelcast-client/lib/proxy/BaseProxy.js:12:33
    at tryCatcher (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/cycerto/ProjectWorkspace/webstorm/caster-client-sdk-nodejs/node_modules/bluebird/js/release/async.js:148:10)
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true }
```

> client: v0.5.0
> server: 3.6

**Comment by mustafaiman** [comment]
Thank you @cycerto for reporting. I can reproduce the problem. Will fix it.
