### ISSUE TITLE
NODEJS Client reconnection issue

### ISSUE THREAD

**Issue by alucarpd86** [hazelcast/hazelcast-nodejs-client#174]
Hi,

i've 2 hazelcast instance running in cluster (version 3.7.2)
i've 6 nodejs client application connected to this cluster. (nodejs client v0.6.0)

After some time, between 5-20 minutes, on some of my NODEJS client i got this stack trace, coming from the hazelcast nodejs library:
```
[2017-05-03 11:56:21.912] [INFO] console - [DefaultLogger] WARN at ClientConnection: Could not connect to address 192.168.0.49:4401

[2017-05-03 11:56:21.915] [INFO] console - { Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:291:12)
    at ClientConnection.write (/opt/convy/app/node_modules/hazelcast-client/lib/invocation/ClientConnection.js:49:21)
    at InvocationService.send (/opt/convy/app/node_modules/hazelcast-client/lib/invocation/InvocationService.js:103:20)
    at InvocationService.invokeSmart (/opt/convy/app/node_modules/hazelcast-client/lib/invocation/InvocationService.js:59:25)
    at InvocationService.invokeOnConnection (/opt/convy/app/node_modules/hazelcast-client/lib/invocation/InvocationService.js:42:21)
    at Heartbeat.heartbeatFunction (/opt/convy/app/node_modules/hazelcast-client/lib/HeartbeatService.js:38:56)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) code: 'EPIPE' }
```

i checked the hazelcast server logs and i've found:
```
2017-05-03 11:56:19 INFO  ClientEndpointManager - [192.168.0.49]:4401 [group] [3.7.2] Destroying ClientEndpoint{conn=Connection[id=25, /192.168.0.49:4401->/192.168.0.68:56499, endpoint=[192.168.0.68]:56499, alive=true, type=NODEJS_CLIENT], principal='ClientPrincipal{uuid='77cd062e-f0ae-40e8-af5e-b96ee025060a', ownerUuid='c55d13f6-3289-479a-84db-8f1186243daf'}', firstConnection=false, authenticated=true}

2017-05-03 11:56:19 INFO  TcpIpConnection - [192.168.0.49]:4401 [group] [3.7.2] Connection[id=25, /192.168.0.49:4401->/192.168.0.68:56499, endpoint=[192.168.0.68]:56499, alive=false, type=NODEJS_CLIENT] closed. Reason: Socket explicitly closed

2017-05-03 11:56:19 INFO  TransactionManagerService - [192.168.0.49]:4401 [group] [3.7.2] Committing/rolling-back alive transactions of client, UUID: 77cd062e-f0ae-40e8-af5e-b96ee025060a

2017-05-03 11:56:19 INFO  ClientEndpointManager - [192.168.0.49]:4401 [group] [3.7.2] Destroying ClientEndpoint{conn=Connection[id=24, /192.168.0.49:4401->/192.168.0.49:57289, endpoint=[192.168.0.49]:57289, alive=true, type=NODEJS_CLIENT], principal='ClientPrincipal{uuid='bb9a97f0-7a91-42dd-9aae-919cbe556b91', ownerUuid='c55d13f6-3289-479a-84db-8f1186243daf'}', firstConnection=false, authenticated=true}

2017-05-03 11:56:19 INFO  TcpIpConnection - [192.168.0.49]:4401 [group] [3.7.2] Connection[id=24, /192.168.0.49:4401->/192.168.0.49:57289, endpoint=[192.168.0.49]:57289, alive=false, type=NODEJS_CLIENT] closed. Reason: Socket explicitly closed

2017-05-03 11:56:19 INFO  TransactionManagerService - [192.168.0.49]:4401 [group] [3.7.2] Committing/rolling-back alive transactions of client, UUID: bb9a97f0-7a91-42dd-9aae-919cbe556b91

2017-05-03 11:56:19 INFO  ClientEndpointManager - [192.168.0.49]:4401 [group] [3.7.2] Destroying ClientEndpoint{conn=Connection[id=23, /192.168.0.49:4401->/192.168.0.49:57288, endpoint=[192.168.0.49]:57288, alive=true, type=NODEJS_CLIENT], principal='ClientPrincipal{uuid='b6de2ee6-b537-4656-be65-1e3347cad408', ownerUuid='c55d13f6-3289-479a-84db-8f1186243daf'}', firstConnection=false, authenticated=true}

2017-05-03 11:56:19 INFO  TcpIpConnection - [192.168.0.49]:4401 [group] [3.7.2] Connection[id=23, /192.168.0.49:4401->/192.168.0.49:57288, endpoint=[192.168.0.49]:57288, alive=false, type=NODEJS_CLIENT] closed. Reason: Socket explicitly closed

2017-05-03 11:56:19 INFO  TransactionManagerService - [192.168.0.49]:4401 [group] [3.7.2] Committing/rolling-back alive transactions of client, UUID: b6de2ee6-b537-4656-be65-1e3347cad408

2017-05-03 11:56:19 INFO  ClientEndpointManager - [192.168.0.49]:4401 [group] [3.7.2] Destroying ClientEndpoint{conn=Connection[id=26, /192.168.0.49:4401->/192.168.0.68:56500, endpoint=[192.168.0.68]:56500, alive=true, type=NODEJS_CLIENT], principal='ClientPrincipal{uuid='65548fa8-cd5a-4d0f-a14c-29d0ff8f860d', ownerUuid='c55d13f6-3289-479a-84db-8f1186243daf'}', firstConnection=false, authenticated=true}

2017-05-03 11:56:19 INFO  TcpIpConnection - [192.168.0.49]:4401 [group] [3.7.2] Connection[id=26, /192.168.0.49:4401->/192.168.0.68:56500, endpoint=[192.168.0.68]:56500, alive=false, type=NODEJS_CLIENT] closed. Reason: Socket explicitly closed

2017-05-03 11:56:19 INFO  TransactionManagerService - [192.168.0.49]:4401 [group] [3.7.2] Committing/rolling-back alive transactions of client, UUID: 65548fa8-cd5a-4d0f-a14c-29d0ff8f860d`
```
When the first exception is thrown on the clients, the nodejs library doesn't raise any events (i'm listening on "connectionClosed" and "connectionOpened") and the heartbeat service continue to try to send heartbeat without any success forever and the client remains disconnected.

Hazelcast server is running with the default configuration.
The NODEJS client is configured with both hazelcast server IP addresses, like:
```
[
        {
          "host": "192.168.0.68",
          "port": "4401"
        },
        {
          "host": "192.168.0.49",
          "port": "4401"
        }
]
```
any ideas? why the hazelcast server  explicitly close the client connections? how can i investigate this further?

**Comment by gAmUssA** [comment]
@alucarpd86 A server doesn't close the connection explicitly. Could you make sure that there were no network issues during disconnect?

**Comment by alucarpd86** [comment]
i've made some further investigations: the problem seems to be orginated on client side because node js library fail to send heartbeats.
in the HeartbeatService.js class, the method this.client.getInvocationService().invokeOnConnection(conn, req) fail but the catch function only print a log.
i noticed that the problem shows when the smartRouting option is enabled but i'm not able to debug the hazelcast library any further.

**Comment by mustafaiman** [comment]
hello @alucarpd86 , I am looking into this issue. However, I cannot reproduce it. The reason HeartbeatService tries to re-connect but `invokeOnConnection` fails is that the client cannot communicate with the server. It is normal behavior that HeartbeatService only logs the error because it keep trying to send heartbeats anyway. We do not want to fail the client directly there as missing some heartbeats is expected in a network for any reason. If you still can reproduce the issue, it would be great to have full logs on all members and clients.

**Comment by mustafaiman** [comment]
I am closing this issue due to inactivity. Feel free to re-open it if you still experience problems.

**Comment by bhushanvadgave** [comment]
@mustafaiman I am seeing below errors of my NodeJS process. This NodeJS process connects to clustered Hazelcast. None of the Hazelcast nodes have been down or restarted.

```
{ Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:306:12)
    at ClientConnection.write (/usr/src/app/node_modules/bot-services/node_modules/hazelcast-client/lib/invocation/ClientConnection.js:49:21)
    at InvocationService.send (/usr/src/app/node_modules/bot-services/node_modules/hazelcast-client/lib/invocation/InvocationService.js:106:20)
    at InvocationService.invokeSmart (/usr/src/app/node_modules/bot-services/node_modules/hazelcast-client/lib/invocation/InvocationService.js:62:25)
    at InvocationService.invokeOnConnection (/usr/src/app/node_modules/bot-services/node_modules/hazelcast-client/lib/invocation/InvocationService.js:45:21)
    at Heartbeat.heartbeatFunction (/usr/src/app/node_modules/bot-services/node_modules/hazelcast-client/lib/HeartbeatService.js:38:56)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'EPIPE' }
[DefaultLogger] WARN at InvocationService: Error sending message to 10.244.7.221:5701 Error: This socket has been ended by the other party
[DefaultLogger] WARN at InvocationService: Error sending message to 10.244.7.220:5701 Error: This socket has been ended by the other party
[DefaultLogger] WARN at HeartbeatService: Error: This socket has been ended by the other party
[DefaultLogger] WARN at HeartbeatService: Error: This socket has been ended by the other party
[DefaultLogger] WARN at ClientConnection: Could not connect to address 10.244.7.221:5701
{ Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:306:12)
    at ClientConnection.write (/usr/src/app/node_modules/bot-services/node_modules/hazelcast-client/lib/invocation/ClientConnection.js:49:21)
    at InvocationService.send (/usr/src/app/node_modules/bot-services/node_modules/hazelcast-client/lib/invocation/InvocationService.js:106:20)
    at InvocationService.invokeSmart (/usr/src/app/node_modules/bot-services/node_modules/hazelcast-client/lib/invocation/InvocationService.js:62:25)
    at InvocationService.invokeOnConnection (/usr/src/app/node_modules/bot-services/node_modules/hazelcast-client/lib/invocation/InvocationService.js:45:21)
    at Heartbeat.heartbeatFunction (/usr/src/app/node_modules/bot-services/node_modules/hazelcast-client/lib/HeartbeatService.js:38:56)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'EPIPE' }
[DefaultLogger] WARN at ClientConnection: Could not connect to address 10.244.7.220:5701

```

**Comment by mustafaiman** [comment]
Hello @bhushanvadgave 
These are warning messages. Did this cause the process to fail or did it eventually recovered? It says connections to `10.244.7.221` and `10.244.7.221` were closed by the other party. It looks like the servers might have decided that your client was dead. A possible cause could be some operation taking so long that it blocked periodic heartbeat events between the client and the servers. Do you perform any long running jobs?

**Comment by serverdevil** [comment]
@mustafaiman What is the general approach to such problems when using the nodejs client? If the event loop is busy with a task that does not have async operations, I presume the heartbeat events will get held up.

**Comment by mustafaiman** [comment]
@serverdevil yes, long running tasks on the event loop might delay heartbeats, causing connectivity problems. If your application runs too many sync long-runnning jobs, there is not much the client can do. However, you might want to increase with heartbeat timeout and heartbeat interval. This will keep the client from disconnecting for a longer time. 
```
            var cfg = new Config.ClientConfig();
            cfg.properties['hazelcast.client.heartbeat.interval'] = 10000;
            cfg.properties['hazelcast.client.heartbeat.timeout'] = 120000;
```
