### ISSUE TITLE
It caught error in v0.6.2, when try authenticate the connection.

### ISSUE THREAD

**Issue by cycerto** [hazelcast/hazelcast-nodejs-client#207]
server: 3.6.1
client: 0.6.2

it caught error, when try authenticate a connection.

file: ClientConnectionManager.js
```
ClientConnectionManager.prototype.getOrConnect = function (address, ownerConnection) {
        ...
        clientConnection.connect().then(function () {
            ...
        }).then(function () {
            return _this.authenticate(clientConnection, ownerConnection);
        }).then(function () {
            ...
        }).catch(function (e) {
            console.error("ErrorDetail in connect:", e);
            result.resolve(null);
        }).finally(function () {
            ...
        });
        ...
};
```

ErrorDetail:
```
RangeError: Index out of range
    at checkOffset (buffer.js:835:11)
    at Buffer.readInt32LE (buffer.js:988:5)
    at ClientMessage.readString (/home/hazelcast-nodejs-client/lib/ClientMessage.js:152:34)
    at Function.ClientAuthenticationCodec.decodeResponse (/home/hazelcast-nodejs-client/lib/codec/ClientAuthenticationCodec.js:75:62)
    at /home/hazelcast-nodejs-client/lib/invocation/ConnectionAuthenticator.js:17:86
    at tryCatcher (/home/hazelcast-nodejs-client/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/hazelcast-nodejs-client/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/homet/hazelcast-nodejs-client/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/hazelcast-nodejs-client/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/hazelcast-nodejs-client/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/hazelcast-nodejs-client/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/hazelcast-nodejs-client/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/hazelcast-nodejs-client/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5) {stack: RangeError: Index out of range
    at checkOffset …mediate [as _immediateCallback] (timers.js:594:5),
message: Index out of range}
```

**Comment by mustafaiman** [comment]
Thank you @cycerto . This is due to a bug in codec we use for communication between server and client. I have prepared a fix for this.
Do you use server 3.6 for production or is it a test environment?

**Comment by cycerto** [comment]
Use server v3.6.1 for production.
