### ISSUE TITLE
Failure "Logging Test no logging" on Windows

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-nodejs-client#348]
```
Logging Test no logging:
 expected log to not have been called but was called 7 times
log([DefaultLogger] %s at %s: %s, WARN, ClientConnectionManager, Could not connect to address localhost:5701) at DefaultLogger.log (C:\jenkins\workspace\NodeJS-8-windows\lib\logging\DefaultLogger.js:9:729)
log(Error: This socket has been ended by the other party) at DefaultLogger.log (C:\jenkins\workspace\NodeJS-8-windows\lib\logging\DefaultLogger.js:9:964)
log([DefaultLogger] %s at %s: %s, WARN, ClusterService, Connection closed to localhost:5701) at DefaultLogger.log (C:\jenkins\workspace\NodeJS-8-windows\lib\logging\DefaultLogger.js:9:729)
log([DefaultLogger] %s at %s: %s, WARN, PartitionService, Error while fetching cluster partition table!) at DefaultLogger.log (C:\jenkins\workspace\NodeJS-8-windows\lib\logging\DefaultLogger.js:9:729)
log(Error: Error: This socket has been ended by the other party) at DefaultLogger.log (C:\jenkins\workspace\NodeJS-8-windows\lib\logging\DefaultLogger.js:9:964)
log([DefaultLogger] %s at %s: %s, INFO, ClusterService, Members received.) at DefaultLogger.log (C:\jenkins\workspace\NodeJS-8-windows\lib\logging\DefaultLogger.js:9:729)
log([Member[ uuid: 78f08eee-b8c0-4034-b607-8c352e9e036b, address: localhost:5701]]) at DefaultLogger.log (C:\jenkins\workspace\NodeJS-8-windows\lib\logging\DefaultLogger.js:9:964)
15:41:10   AssertError: expected log to not have been called but was called 7 times
  log([DefaultLogger] %s at %s: %s, WARN, ClientConnectionManager, Could not connect to address localhost:5701) at DefaultLogger.log (lib\logging\DefaultLogger.js:9:729)
  log(Error: This socket has been ended by the other party) at DefaultLogger.log (lib\logging\DefaultLogger.js:9:964)
  log([DefaultLogger] %s at %s: %s, WARN, ClusterService, Connection closed to localhost:5701) at DefaultLogger.log (lib\logging\DefaultLogger.js:9:729)
  log([DefaultLogger] %s at %s: %s, WARN, PartitionService, Error while fetching cluster partition table!) at DefaultLogger.log (lib\logging\DefaultLogger.js:9:729)
  log(Error: Error: This socket has been ended by the other party) at DefaultLogger.log (lib\logging\DefaultLogger.js:9:964)
  log([DefaultLogger] %s at %s: %s, INFO, ClusterService, Members received.) at DefaultLogger.log (lib\logging\DefaultLogger.js:9:729)
  log([Member[ uuid: 78f08eee-b8c0-4034-b607-8c352e9e036b, address: localhost:5701]]) at DefaultLogger.log (lib\logging\DefaultLogger.js:9:964)
  at Object.fail (node_modules\sinon\lib\sinon\assert.js:96:21)
  at failAssertion (node_modules\sinon\lib\sinon\assert.js:55:16)
  at Object.assert.(anonymous function) [as notCalled] (node_modules\sinon\lib\sinon\assert.js:80:13)
  at test\LoggingTest.js:88:33
  at tryCatcher (node_modules\bluebird\js\release\util.js:16:23)
  at Promise._settlePromiseFromHandler (node_modules\bluebird\js\release\promise.js:512:31)
  at Promise._settlePromise (node_modules\bluebird\js\release\promise.js:569:18)
  at Promise._settlePromise0 (node_modules\bluebird\js\release\promise.js:614:10)
  at Promise._settlePromises (node_modules\bluebird\js\release\promise.js:693:18)
  at Async._drainQueue (node_modules\bluebird\js\release\async.js:133:16)
  at Async._drainQueues (node_modules\bluebird\js\release\async.js:143:10)
  at Immediate.Async.drainQueues (node_modules\bluebird\js\release\async.js:17:14)
```

This error has been seen on testsuite run with node.js 8 executed on Windows machine, see:
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/NodeJS-8-windows/22/consoleFull

**Comment by mustafaiman** [comment]
Logging module has been changed significantly recently. I have never seen this issue a second time since it is first encountered in september. I am closing this issue now. If you encounter this again, please re-open with up-to-date logs.
