### ISSUE TITLE
Partition ID cannot be negative!

### ISSUE THREAD

**Issue by jcaprice** [hazelcast/hazelcast-nodejs-client#423]
Upon connecting the Node.js client to a newly formed cluster, I sometimes receive the below error on the client. The client is able to connect to the cluster normally if restarted.

```
Unhandled rejection TypeError: Partition ID cannot be negative!
    at /Users/user/node_modules/hazelcast-client/lib/protocol/ErrorFactory.js:42:118
    at ClientErrorFactory.createError (/Users/user/node_modules/hazelcast-client/lib/protocol/ErrorFactory.js:84:20)
    at ClientErrorFactory.createErrorFromClientMessage (/Users/user/node_modules/hazelcast-client/lib/protocol/ErrorFactory.js:79:21)
    at InvocationService.processResponse (/Users/user/node_modules/hazelcast-client/lib/invocation/InvocationService.js:292:61)
    at processResponseCallback (/Users/user/node_modules/hazelcast-client/lib/invocation/ClientConnectionManager.js:79:49)
    at Socket.<anonymous> (/Users/user/node_modules/hazelcast-client/lib/invocation/ClientConnection.js:122:17)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:122:17)
```

**Comment by puzpuzpuz** [comment]
Closing this one as it seems to be something that was fixed in both v3.12.x and v4.x.
