### ISSUE TITLE
Scaling down Hazelcast cluster causes errors in client with `redoOperation` enabled

### ISSUE THREAD

**Issue by googlielmo** [hazelcast/hazelcast-nodejs-client#506]
Hazelcast client version: 3.12.1
Hazelcast server version: 3.12.3
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: 2 then scaled up to 4 and then scaled back to 2 again 
OS version : Linux ip-172-31-39-172 4.15.0-1051-aws #53-Ubuntu SMP Wed Sep 18 13:35:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

#### Expected behaviour

A client with `redoOperation` enabled is connected to a Hazelcast Cloud Dedicated cluster with 2 members and starts issuing periodical requests. 
The cluster is scaled up from 2 to 4 members. The client is unaffected.
Then the cluster is scaled back down from 4 to 2 members. The client should be unaffected. 

#### Actual behaviour

When the cluster is scaled back down from 4 to 2 members the client logs errors and stops issuing any new request to the server (does not seem to disconnect though).

#### Steps to reproduce the behaviour

Create Hazelcast cluster with 2 members.

Run a client program that connects and issues periodical requests, such as the following.

```
var async = require('async');
var Client = require('hazelcast-client').Client;
var ClientConfig = require('hazelcast-client').Config.ClientConfig;

function createClientConfig() {
    var fs = require('fs');
    var cfg = new ClientConfig();
    cfg.networkConfig.redoOperation = true;
    cfg.networkConfig.connectionAttemptLimit = 10;
    cfg.properties['hazelcast.client.statistics.enabled'] = true;
    cfg.properties['hazelcast.client.statistics.period.seconds'] = 1;
    return cfg;
}

var cfg = createClientConfig();

Client.newHazelcastClient(cfg).then(function (hazelcastClient) {
    var client = hazelcastClient;
    var map;
    hazelcastClient.getMap('map').then(function (mp) {
      map = mp;

      map.put('key', 'value').then(function () {
          return map.get('key');
      }).then((res) => {
          if(res === 'value')
          {
              console.log("Connection Successful!");
              console.log("Now, `map` will be filled with random entries.");

              async.whilst(() => {
                return true;
              },(next) => {
                var randomKey = Math.floor(Math.random() * 100000);
                map.put('key' + randomKey, 'value' + randomKey).then(function () {
                    map.get('key' + randomKey);
                    if (randomKey % 10 == 0) {
                        map.size().then((size) => console.log(`map size: ${size}`));
                    }
                    next();
                });
              },(err) => {
                client.shutdown();
              });
          }
          else {
              throw new Error("Connection failed, check your configuration.");
          }
      });
    });
});
```

Now scale the cluster up to 4 members. Client will continue to issue requests.
Scale down to 2 members again, the following error will be logged and the program will hang.

```
[DefaultLogger] WARN at ClientConnectionManager: Could not connect to address 33.11.106.108:30023
{ Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:364:12)
    at PipelinedWriter.process (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/hazelcast-client/lib/invocation/ClientConnection.js:87:21)
    at /home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/hazelcast-client/lib/invocation/ClientConnection.js:63:57
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'EPIPE' }
[DefaultLogger] WARN at ClusterService: Connection closed to 100.96.6.2:30023
[DefaultLogger] WARN at ClientConnectionManager: Could not connect to address 33.11.118.111:30023
{ Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:364:12)
    at PipelinedWriter.process (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/hazelcast-client/lib/invocation/ClientConnection.js:87:21)
    at /home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/hazelcast-client/lib/invocation/ClientConnection.js:63:57
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'EPIPE' }
[DefaultLogger] WARN at ClusterService: Connection closed to 100.96.7.2:30023
[DefaultLogger] WARN at ClusterService: Error: Connection timed-out
[DefaultLogger] WARN at ClusterService: Error: Connection timed-out
[DefaultLogger] INFO at ClusterService: Members received.
[ Member {
    address: 
     Address {
       host: '100.96.6.2',
       port: 30023,
       type: 4,
       addrStr: '100.96.6.2:30023' },
    uuid: 'ab16f757-8444-4172-99f9-f8fa0e87fcf0',
    isLiteMember: false,
    attributes: { 'hazelcast.partition.group.zone': 'eu-central-1c' } },
  Member {
    address: 
     Address {
       host: '100.96.7.2',
       port: 30023,
       type: 4,
       addrStr: '100.96.7.2:30023' },
    uuid: '3c3136a1-2c97-4e7e-bcc9-29e37d4007f9',
    isLiteMember: false,
    attributes: { 'hazelcast.partition.group.zone': 'eu-central-1c' } },
  Member {
    address: 
     Address {
       host: '100.96.9.2',
       port: 30023,
       type: 4,
       addrStr: '100.96.9.2:30023' },
    uuid: '1da5da20-431e-47a2-b2a7-da77c4fb3b8a',
    isLiteMember: false,
    attributes: { 'hazelcast.partition.group.zone': 'eu-central-1c' } },
  Member {
    address: 
     Address {
       host: '100.96.10.2',
       port: 30023,
       type: 4,
       addrStr: '100.96.10.2:30023' },
    uuid: '52e06012-444d-4149-885f-b4fe0c0c9730',
    isLiteMember: false,
    attributes: { 'hazelcast.partition.group.zone': 'eu-central-1c' } } ]
[DefaultLogger] INFO at ClusterService: Member[ uuid: ab16f757-8444-4172-99f9-f8fa0e87fcf0, address: 100.96.6.2:30023] removed from cluster
[DefaultLogger] INFO at ClusterService: Member[ uuid: 3c3136a1-2c97-4e7e-bcc9-29e37d4007f9, address: 100.96.7.2:30023] removed from cluster
[DefaultLogger] WARN at ClientConnectionManager: Could not connect to address 33.11.101.6:30023
{ Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:364:12)
    at PipelinedWriter.process (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/hazelcast-client/lib/invocation/ClientConnection.js:87:21)
    at /home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/hazelcast-client/lib/invocation/ClientConnection.js:63:57
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'EPIPE' }
[DefaultLogger] WARN at ClusterService: Connection closed to 100.96.9.2:30023
[DefaultLogger] INFO at ConnectionAuthenticator: Connection to 100.96.9.2:30023 authenticated
[DefaultLogger] INFO at ClusterService: Members received.
[ Member {
    address: 
     Address {
       host: '100.96.9.2',
       port: 30023,
       type: 4,
       addrStr: '100.96.9.2:30023' },
    uuid: '1da5da20-431e-47a2-b2a7-da77c4fb3b8a',
    isLiteMember: false,
    attributes: { 'hazelcast.partition.group.zone': 'eu-central-1c' } },
  Member {
    address: 
     Address {
       host: '100.96.10.2',
       port: 30023,
       type: 4,
       addrStr: '100.96.10.2:30023' },
    uuid: '52e06012-444d-4149-885f-b4fe0c0c9730',
    isLiteMember: false,
    attributes: { 'hazelcast.partition.group.zone': 'eu-central-1c' } } ]
[DefaultLogger] WARN at ClientConnectionManager: Could not connect to address 33.11.120.0:30023
{ Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:364:12)
    at PipelinedWriter.process (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/hazelcast-client/lib/invocation/ClientConnection.js:87:21)
    at /home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/hazelcast-client/lib/invocation/ClientConnection.js:63:57
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'EPIPE' }
[DefaultLogger] WARN at ClusterService: Connection closed to 100.96.10.2:30023
[DefaultLogger] WARN at ClientConnectionManager: Could not connect to address 33.11.106.108:30023
{ Error: connect ETIMEDOUT 33.11.106.108:30023
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '33.11.106.108',
  port: 30023 }
Unhandled rejection Error: Invocation 591988) reached its deadline.
    at new InvocationTimeoutError (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/hazelcast-client/lib/HazelcastError.js:123:28)
    at InvocationService.rejectIfNotRetryable (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/hazelcast-client/lib/invocation/InvocationService.js:280:40)
    at InvocationService.notifyError (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/hazelcast-client/lib/invocation/InvocationService.js:247:18)
    at /home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/hazelcast-client/lib/invocation/InvocationService.js:191:19
    at tryCatcher (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/ubuntu/hazelcast-cloud-nodejs-sample-client-guglielmo-net-04/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

[DefaultLogger] INFO at ConnectionAuthenticator: Connection to 100.96.10.2:30023 authenticated
[DefaultLogger] WARN at ClientConnectionManager: Could not connect to address 33.11.118.111:30023
{ Error: connect ETIMEDOUT 33.11.118.111:30023
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '33.11.118.111',
  port: 30023 }
```

**Comment by puzpuzpuz** [comment]
Closing this one as `redoOperation` support was only added in v3.12.4 (see #662)
