### ISSUE TITLE
UnhandledPromiseRejectionWarning on 3.12.3 client

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#539]
It's enough to start a client with the default config and no IMDG members available on the localhost, to see the following warning:
```
(node:12795) UnhandledPromiseRejectionWarning: Error: Unable to connect to any of the following addresses: localhost:5701
    at new IllegalStateError (/home/puzpuzpuz/projects/hazelcast-client-proxy/node_modules/hazelcast-client/lib/HazelcastError.js:73:28)
    at ClusterService.tryConnectingToAddresses (/home/puzpuzpuz/projects/hazelcast-client-proxy/node_modules/hazelcast-client/lib/invocation/ClusterService.js:217:29)
    at /home/puzpuzpuz/projects/hazelcast-client-proxy/node_modules/hazelcast-client/lib/invocation/ClusterService.js:240:30
    at tryCatcher (/home/puzpuzpuz/projects/hazelcast-client-proxy/node_modules/hazelcast-client/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/puzpuzpuz/projects/hazelcast-client-proxy/node_modules/hazelcast-client/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/puzpuzpuz/projects/hazelcast-client-proxy/node_modules/hazelcast-client/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/puzpuzpuz/projects/hazelcast-client-proxy/node_modules/hazelcast-client/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/puzpuzpuz/projects/hazelcast-client-proxy/node_modules/hazelcast-client/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/puzpuzpuz/projects/hazelcast-client-proxy/node_modules/hazelcast-client/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/puzpuzpuz/projects/hazelcast-client-proxy/node_modules/hazelcast-client/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/puzpuzpuz/projects/hazelcast-client-proxy/node_modules/hazelcast-client/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/puzpuzpuz/projects/hazelcast-client-proxy/node_modules/hazelcast-client/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:456:21)
(node:12795) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by puzpuzpuz** [comment]
Closing this one as it was a false positive alarm. The promise rejection wasn't handled at the app level.
