### ISSUE TITLE
Flaky ClientBackupAcksTest

### ISSUE THREAD

**Issue by puzpuzpuz** [hazelcast/hazelcast-nodejs-client#629]
`ClientBackupAcksTest` sometimes fails on Jenkins due backup ack timeout. See http://jenkins.hazelcast.com/job/NodeJS-pr-builder/625/testReport/junit/(root)/should%20receive%20backup%20acks%20in%20smart%20mode/ClientBackupAcksTest_should_receive_backup_acks_in_smart_mode/

```
ClientBackupAcksTest should receive backup acks in smart mode

Error Message
Invocation 7 failed because of missed backup acks
Stacktrace
Error: Invocation 7 failed because of missed backup acks
    at new IndeterminateOperationStateError (lib/core/HazelcastError.js:18:12810)
    at Invocation.detectAndHandleBackupTimeout (lib/invocation/InvocationService.js:32:2821)
    at Timeout.Util_1.scheduleWithRepetition [as _onTimeout] (lib/invocation/InvocationService.js:35:2947)
```

**Comment by puzpuzpuz** [comment]
Raising priority for this one as it frequently shows up in CI runs

**Comment by puzpuzpuz** [comment]
Closing in favor of #616
