### ISSUE TITLE
setTtl updates ttl for entry.MapProxyTest - Near Cache enabled: true setTtl updates ttl for entry 

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-nodejs-client#864]
Increase setTtl value:

Stacktrace:

Error Message
```
expected null to equal 'val10'
Stacktrace
AssertionError: expected null to equal 'val10'
    at Context.<anonymous> (test/integration/backward_compatible/map/MapProxyTest.js:133:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by srknzl** [comment]
Also putIfAbsent_with_ttl failed on http://jenkins.hazelcast.com/job/NodeJS-pr-builder/1320/testReport/junit/Node.js%20Client%20Tests/MapProxyTest%20%20-%20Near%20Cache%20enabled_%20false/putIfAbsent_with_ttl/

```
Error Message
expected null to equal 'new-val'
Stacktrace
    at Context.<anonymous> (test/integration/backward_compatible/map/MapProxyTest.js:332:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
